services:
  pico_sdk:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - ./build:/root/app/build
      - ./pico_lib:/root/pico_lib
      # - ./.pico-sdk:/root/.pico-sdk
      - ./main.cpp:/root/app/main.cpp:ro
      - ./lwipopts.h:/root/app/lwipopts.h:ro
      - ./CMakeLists.txt:/root/app/CMakeLists.txt
    command: ["sleep", "infinity"]
