services:
  pico_sdk:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.dev.master
    network_mode: host
    volumes:
      - ./build:/root/app/build
      - ./pico_lib:/root/pico_lib
      - ./extern:/root/app/extern:ro
      - ./main.cpp:/root/app/main.cpp:ro
      - ./docs:/root/app/docs
      - ./CMakeLists.txt:/root/app/CMakeLists.txt
    command: ["sleep", "infinity"]
